name: release

#on:
#  schedule:
#    - cron: "0 0 * * *"

on: [workflow_dispatch]

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v1
      - name: Install AU
        run: Install-Module au -Force
      - name: Update Template
        id: update_template
        working-directory: twingate
        run: .\update.ps1
      - name: Cat Content
        id: cat_content
        working-directory: twingate
        run:  echo "::set-output name=out::$(cat twingate.nuspec)"
      - name: Check Contains
        id: check_contains
        if: ${{ !contains(steps.cat_content.outputs.out, '1.0.18.11084') }}
        working-directory: twingate
        run: cat twingate.nuspec
      - name: Choco Package
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack twingate/twingate.nuspec
      - run: |
          dir
#      - name: workingdirectory
#        working-directory: twingate
