name: release

#on:
#  schedule:
#    - cron: "0 0 * * *"

on: [workflow_dispatch]

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v1
      - run: |
          ls
      - run: |
          dir
#      - run: |
#          cd twingate
      - run: |
          dir
        working-directory: twingate
      - run: |
          dir
