name: release

#on:
#  schedule:
#    - cron: "0 0 * * *"

on: [workflow_dispatch]

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v1
      - name: Install AU
        run: Install-Module au
      - run: |
          ls
      - run: |
          dir
#      - run: |
#          cd twingate
      - name: workingdirectory
        working-directory: twingate
        run: |
          dir
      - run: |
          dir
